### PR TITLE
Submission by Dhriti

### PR DESCRIPTION
**Pull request by DhRiTiD**

### CODE REVIEW

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Hey @DhRiTiD ,
can you upload both css and HTML file here

**Comment by DhRiTiD** [comment]
the file format is not supported her, I'm sending u a link, dwnld from there

[style.css](https://github.com/DhRiTiD/myprofile/blob/main/style.css)

[profile.html](https://github.com/DhRiTiD/myprofile/blob/main/profile.html)

**Comment by Shrey-Mehra** [comment]
then upload the folder where you save your code in projects

**Comment by Shrey-Mehra** [comment]
the files will auto matically uploaded

**Comment by DhRiTiD** [comment]
> the files will auto matically uploaded

not supported here, do u want me to upload the folder in the 'projects 'folder in this repo?

image

**Comment by Shrey-Mehra** [comment]
yes

**Comment by Shrey-Mehra** [comment]
ok thanks will merge it after reviewing

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Here  You have to write your name and mail

image

**Comment by Shrey-Mehra** [comment]
Hey @DhRiTiD ,
kindly fill out this form for goodies
https://link.codethetech.tech/surprise

**Review by Shrey-Mehra — APPROVED** [review]

**Comment by Shreeya-Rani** [comment]
Hey Dhriti,
We'll merge this website for now but you need to work on the responsiveness

**Comment by DhRiTiD** [comment]
> Hey Dhriti, We'll merge this website for now but you need to work on the responsiveness

yeah!

**Comment by DhRiTiD** [comment]
> Here You have to write your name and mail
> 
> image

done, also form submitted

**Pull request merged**
